### ISSUE TITLE
Issue with S3 bucket connectivity -  Failed to create engine: error unmarshalling flow: unable to compile expression '*****': error parsing expression

### ISSUE THREAD

**Issue by neethuabacker** [retgits/flogo-components#15] opened 2019-11-12 16:56 UTC
Hi,

I keep getting this error
Failed to create engine: error unmarshalling flow: unable to compile expression '****': error parsing expression
This i get for the awsaccess key. I try to put the value within double quotes, but that doesnt work either. Not sure why its trying to parse the awsaccess key, its just an alphanumeric key

Thanks

**Comment by neethuabacker** [comment] 2019-11-12 19:01
attaching the app json minus the key and secret values. 

[s_3_operations (1).zip](https://github.com/retgits/flogo-components/files/3837746/s_3_operations.1.zip)

**Comment by retgits** [comment] 2019-11-12 21:12
Just to add our conversation on Gitter here as well:
I just ran the test cases in the repo and they work perfectly, so it’s not an issue in the code of the S3 activity. It might be an issue in either the UI or the way the UI passes the variables to the engine. The Flogo UI team is looking at potential issues.

**Comment by neethuabacker** [comment] 2019-11-13 18:34
This issue was not related to the connector, I had to restart the flogo container for some reason it was not saving changes. However I am seeing another issue. 

Error:
github.com/project-flogo/flow/model/simple.(*TaskBehavior).Eval
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/model/simple/taskbehavior.go:90
github.com/project-flogo/flow/instance.(*IndependentInstance).execTask
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/instance/instances.go:255
github.com/project-flogo/flow/instance.(*IndependentInstance).DoStep
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/instance/instances.go:199
github.com/project-flogo/flow.(*FlowAction).Run.func1
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/action.go:300
2019-11-13T13:32:01.030-0500    ERROR   [flogo.flow] -  Error evaluating activity 'amazons3_4'[github.com/project-flogo/legacybridge] - interface conversion: interface {} is nil, not string
github.com/project-flogo/core/support/log.(*zapLoggerImpl).Errorf
        /go/pkg/mod/github.com/project-flogo/core@v0.9.4/support/log/zap.go:65
github.com/project-flogo/flow/model/simple.(*TaskBehavior).Eval
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/model/simple/taskbehavior.go:93
github.com/project-flogo/flow/instance.(*IndependentInstance).execTask
        /go/pkg/mod/github.com/project-flogo/flow@v0.9.4/instance/instances.go:255

**Comment by retgits** [comment] 2019-11-13 19:04
It looks like there is an issue with the https://github.com/project-flogo/legacybridge project in combination with this code. I know the team built it to solve a few issues when they broke backward compatibility in activities but I'm not sure what it exactly does. You might want to check with the Flogo core team why this error exists.

**Comment by neethuabacker** [comment] 2019-11-13 19:07
okay, i will raise a case on flogo git and reference this issue

**Comment by neethuabacker** [comment] 2019-11-15 20:25
Hi, was there a new release to solve this? Mainly it is asking not to pass null on optional fields. Against https://github.com/TIBCOSoftware/flogo/issues/515 I was told this has to be fixed in the connector itself.

**Comment by retgits** [comment] 2019-11-15 20:31
Not exactly, the issue is still that the legacy bridge passes the context with the values provided in the JSON to the legacy activity. If there's no value associated with it, it passes {}. Having said that, I have contributed a new activity to the main aws-contrib repo https://github.com/project-flogo/aws-contrib/pull/7. As soon as the PR is accepted and merged, you'll be able to use it.

**Comment by neethuabacker** [comment] 2019-11-15 20:32
okay, thanks!! i checked there already was not able to see the activity so I thought I should expect a new release here
. Thanks !

**Comment by retgits** [comment] 2019-11-22 19:53
My new activity has been merged into the master branch at https://github.com/project-flogo/aws-contrib, so I suggest using that one 😄 I'll close the issue here, thanks for reporting it!

**Closed by retgits** 2019-11-22 19:53 UTC
